In [29]:
import numpy as np

In [30]:
a = np.arange(15)

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
a.dtype

dtype('int32')

In [34]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
a.reshape(3, 5).max(axis=1)

array([ 4,  9, 14])

In [36]:
a.reshape(3, 5).max(axis=0)

array([10, 11, 12, 13, 14])

In [37]:
! pip install pandas


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
import pandas as pd
from CustomerDAO import CustomerDAO

In [39]:
dao = CustomerDAO('customer_db.db')

In [40]:
customers = dao.findAll()

In [41]:
df_customers = pd.DataFrame(customers)

In [42]:
df_customers

id first_name  last_name                         email      gender  \
0       1    Sherman     Piatek        spiatek0@bloomberg.com        Male   
1       2       Rosa  Fattorini    rfattorini1@cloudflare.com      Female   
2       3     Rockie     McGirr           rmcgirr2@abc.net.au        Male   
3       4     Franny    Bindley            fbindley3@phoca.cz      Female   
4       5     Malina     Kevern            mkevern4@google.it      Female   
..    ...        ...        ...                           ...         ...   
995   996    Dulcine    Warlowe  dwarlowern@sciencedirect.com      Female   
996   997      Monte    Rieflin   mrieflinro@miitbeian.gov.cn        Male   
997   998     Reagen    Ogborne        rogbornerp@arizona.edu        Male   
998   999    Caitrin    Cressar        ccressarrq@gizmodo.com  Non-binary   
999  1000    Emiline    Kopisch        ekopischrr@spotify.com      Female   

         ip_address  
0    74.243.166.225  
1    16.213.105.147  
2     107.97.94.121  
3      95.80.68.237  
4    184.161.76.153  
..              ...  
995   139.225.69.18  
996   23.240.28.169  
997    25.172.137.7  
998  201.38.211.116  
999   93.174.13.233  

[1000 rows x 6 columns]

In [44]:
df_customers.head()

id first_name  last_name                       email  gender  \
0   1    Sherman     Piatek      spiatek0@bloomberg.com    Male   
1   2       Rosa  Fattorini  rfattorini1@cloudflare.com  Female   
2   3     Rockie     McGirr         rmcgirr2@abc.net.au    Male   
3   4     Franny    Bindley          fbindley3@phoca.cz  Female   
4   5     Malina     Kevern          mkevern4@google.it  Female   

       ip_address  
0  74.243.166.225  
1  16.213.105.147  
2   107.97.94.121  
3    95.80.68.237  
4  184.161.76.153

In [45]:
df_customers.tail()

id first_name last_name                         email      gender  \
995   996    Dulcine   Warlowe  dwarlowern@sciencedirect.com      Female   
996   997      Monte   Rieflin   mrieflinro@miitbeian.gov.cn        Male   
997   998     Reagen   Ogborne        rogbornerp@arizona.edu        Male   
998   999    Caitrin   Cressar        ccressarrq@gizmodo.com  Non-binary   
999  1000    Emiline   Kopisch        ekopischrr@spotify.com      Female   

         ip_address  
995   139.225.69.18  
996   23.240.28.169  
997    25.172.137.7  
998  201.38.211.116  
999   93.174.13.233

In [46]:
df_customers.describe()

id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [47]:
df_customers.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'ip_address'], dtype='object')

In [51]:
df_customers.first_name

0      Sherman
1         Rosa
2       Rockie
3       Franny
4       Malina
        ...   
995    Dulcine
996      Monte
997     Reagen
998    Caitrin
999    Emiline
Name: first_name, Length: 1000, dtype: object

In [52]:
df_customers[( (df_customers['gender']=='Male') & (df_customers['email'].str.contains('.edu')))]

id first_name  last_name                      email gender  \
14    15    Talbert      Imlen        timlene@cornell.edu   Male   
38    39     Curran   Stoggles    cstoggles12@harvard.edu   Male   
40    41     Husein    Musterd        hmusterd14@ucsd.edu   Male   
112  113    Niccolo  Liddicoat       nliddicoat34@unc.edu   Male   
122  123   Sherlock    Courcey         scourcey3e@unc.edu   Male   
160  161      Danya     Yonnie          dyonnie4g@psu.edu   Male   
193  194    Patrice  Livermore  plivermore5d@columbia.edu   Male   
237  238    Baldwin   Ganiclef        bganiclef6l@psu.edu   Male   
261  262       Mart   Dimanche       mdimanche79@tamu.edu   Male   
289  290       Beck     Dinkin          bdinkin81@psu.edu   Male   
323  324      Morey    McVicar        mmcvicar8z@ucla.edu   Male   
374  375     Pieter     Galpin     pgalpinae@virginia.edu   Male   
517  518      Colet    Valasek         cvalaseked@mit.edu   Male   
584  585   Hartwell    Giovani        hgiovanig8@yale.edu   Male   
592  593     Jessey    Fiddian     jfiddiangg@arizona.edu   Male   
621  622      Eldin  Tomkowicz      etomkowiczh9@yale.edu   Male   
629  630    Rickert    Gilbart        rgilbarthh@tamu.edu   Male   
652  653       Burg      Vears           bvearsi4@psu.edu   Male   
744  745    Kristos      Hesse           khesseko@umn.edu   Male   
778  779    Shaughn     Voules         svouleslm@ucsd.edu   Male   
825  826    Leeland  Whiteford       lwhitefordmx@umn.edu   Male   
831  832      Grace   Antoniak       gantoniakn3@yale.edu   Male   
997  998     Reagen    Ogborne     rogbornerp@arizona.edu   Male   

          ip_address  
14     33.76.234.252  
38   203.244.187.215  
40    17.202.120.108  
112   106.71.112.178  
122   206.246.94.173  
160   237.184.218.48  
193   158.24.108.180  
237   213.224.156.23  
261     178.31.60.27  
289   197.70.154.200  
323    142.22.43.112  
374    79.100.16.170  
517   187.178.10.237  
584      1.10.36.117  
592   204.101.249.56  
621     94.138.5.224  
629    0.170.188.194  
652  138.131.144.101  
744   238.134.110.49  
778    226.32.52.218  
825    131.168.37.75  
831    167.3.176.196  
997     25.172.137.7

In [53]:
df_customers['upper_last_name'] = df_customers['last_name'].str.upper()

In [54]:
df_customers

id first_name  last_name                         email      gender  \
0       1    Sherman     Piatek        spiatek0@bloomberg.com        Male   
1       2       Rosa  Fattorini    rfattorini1@cloudflare.com      Female   
2       3     Rockie     McGirr           rmcgirr2@abc.net.au        Male   
3       4     Franny    Bindley            fbindley3@phoca.cz      Female   
4       5     Malina     Kevern            mkevern4@google.it      Female   
..    ...        ...        ...                           ...         ...   
995   996    Dulcine    Warlowe  dwarlowern@sciencedirect.com      Female   
996   997      Monte    Rieflin   mrieflinro@miitbeian.gov.cn        Male   
997   998     Reagen    Ogborne        rogbornerp@arizona.edu        Male   
998   999    Caitrin    Cressar        ccressarrq@gizmodo.com  Non-binary   
999  1000    Emiline    Kopisch        ekopischrr@spotify.com      Female   

         ip_address upper_last_name  
0    74.243.166.225          PIATEK  
1    16.213.105.147       FATTORINI  
2     107.97.94.121          MCGIRR  
3      95.80.68.237         BINDLEY  
4    184.161.76.153          KEVERN  
..              ...             ...  
995   139.225.69.18         WARLOWE  
996   23.240.28.169         RIEFLIN  
997    25.172.137.7         OGBORNE  
998  201.38.211.116         CRESSAR  
999   93.174.13.233         KOPISCH  

[1000 rows x 7 columns]